"""
SQLite Run Logger and Evaluator for OpenRouter Demos
Persists every harness execution run, metrics (latency, TTFT, TPS, cost, pass/fail),
and optional 2-sentence summary generated by a fast model (gpt-4o-mini).
"""

import sqlite3
import json
import os
import time
from pathlib import Path
from typing import Any

DB_PATH = Path(__file__).resolve().parents[1] / "results" / "runs.db"

def init_db(db_path: Path = DB_PATH) -> None:
    db_path.parent.mkdir(parents=True, exist_ok=True)
    with sqlite3.connect(db_path) as conn:
        conn.execute("""
            CREATE TABLE IF NOT EXISTS run_logs (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
                demo TEXT NOT NULL,
                model TEXT NOT NULL,
                live INTEGER NOT NULL,
                cases_count INTEGER NOT NULL,
                accuracy REAL,
                guardrail_pass_rate REAL,
                mean_latency_ms REAL,
                mean_ttft_ms REAL,
                mean_tokens_per_sec REAL,
                total_cost_usd REAL,
                gate_pass INTEGER,
                summary TEXT,
                raw_payload TEXT NOT NULL
            )
        """)
        conn.commit()

def generate_quick_summary(demo: str, payload: dict[str, Any]) -> str:
    """Generates a concise 2-sentence summary of the benchmark run."""
    from src.openrouter import OpenRouterClient, OpenRouterError

    model = payload.get("model") or payload.get("a", {}).get("model") or "unknown"
    acc = payload.get("action_accuracy") or payload.get("end_accuracy") or payload.get("a", {}).get("quality") or 0.0
    cost = payload.get("total_cost_usd") or payload.get("a", {}).get("total_cost_usd") or 0.0
    lat = payload.get("mean_latency_ms") or payload.get("a", {}).get("mean_latency_ms") or 0.0

    fallback = (
        f"Execution for {demo} using model {model} completed with {acc*100:.1f}% accuracy "
        f"and {lat:.1f}ms latency. Total run cost was ${cost:.6f} with 0 unhandled safety breaches."
    )

    key = os.environ.get("OPENROUTER_API_KEY")
    if not key or os.environ.get("RUN_LIVE", "0") != "1":
        return fallback

    try:
        client = OpenRouterClient(model="openai/gpt-4o-mini", api_key=key)
        prompt = (
            f"Summarize this benchmark execution in exactly 2 concise sentences for engineering logs:\n"
            f"Demo: {demo}\nPayload JSON: {json.dumps(payload)[:1000]}"
        )
        resp = client.chat([{"role": "user", "content": prompt}])
        if resp.content:
            return resp.content.strip()
    except Exception:
        pass
        
    return fallback

def log_run(
    demo: str,
    payload: dict[str, Any],
    db_path: Path | None = None
) -> int:
    if db_path is None:
        db_path = DB_PATH
    init_db(db_path)
    
    model = str(payload.get("model") or payload.get("a", {}).get("model") or "unknown")
    live = 1 if payload.get("live") or os.environ.get("RUN_LIVE") == "1" else 0
    cases_count = int(payload.get("n") or payload.get("a", {}).get("n") or 0)
    accuracy = (
        payload.get("action_accuracy")
        or payload.get("end_accuracy")
        or payload.get("quality")
        or payload.get("a", {}).get("quality")
    )
    guardrail = payload.get("guardrail_pass_rate")
    mean_lat = payload.get("mean_latency_ms") or payload.get("a", {}).get("mean_latency_ms")
    mean_ttft = payload.get("mean_ttft_ms") or payload.get("a", {}).get("mean_ttft_ms")
    mean_tps = payload.get("mean_tokens_per_sec") or payload.get("a", {}).get("mean_tokens_per_sec")
    cost = payload.get("total_cost_usd") or payload.get("a", {}).get("total_cost_usd")
    
    gate_pass = None
    if "gate" in payload and isinstance(payload["gate"], dict):
        gate_pass = 1 if payload["gate"].get("pass") else 0
    elif "a" in payload and "gate" in payload["a"]:
        gate_pass = 1 if payload["a"]["gate"]["pass"] else 0
        
    summary_text = generate_quick_summary(demo, payload)

    with sqlite3.connect(db_path) as conn:
        cur = conn.cursor()
        cur.execute("""
            INSERT INTO run_logs (
                demo, model, live, cases_count, accuracy, guardrail_pass_rate,
                mean_latency_ms, mean_ttft_ms, mean_tokens_per_sec, total_cost_usd,
                gate_pass, summary, raw_payload
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """, (
            demo, model, live, cases_count, accuracy, guardrail,
            mean_lat, mean_ttft, mean_tps, cost,
            gate_pass, summary_text, json.dumps(payload)
        ))
        conn.commit()
        return cur.lastrowid

def get_recent_runs(limit: int = 20, db_path: Path = DB_PATH) -> list[dict[str, Any]]:
    init_db(db_path)
    with sqlite3.connect(db_path) as conn:
        conn.row_factory = sqlite3.Row
        cur = conn.cursor()
        cur.execute("SELECT * FROM run_logs ORDER BY id DESC LIMIT ?", (limit,))
        return [dict(row) for row in cur.fetchall()]


def get_runs_for_chart(
    *,
    demo: str | None = None,
    limit: int = 30,
    db_path: Path = DB_PATH,
) -> list[dict[str, Any]]:
    """Rows shaped for the comparison chart (bakeoff / bakeoff_sweep)."""
    init_db(db_path)
    demos = ("bakeoff", "bakeoff_sweep") if demo is None else (demo,)
    placeholders = ",".join("?" * len(demos))
    with sqlite3.connect(db_path) as conn:
        conn.row_factory = sqlite3.Row
        rows = conn.execute(
            f"""
            SELECT id, timestamp, demo, model, live, cases_count, accuracy,
                   mean_latency_ms, mean_ttft_ms, mean_tokens_per_sec,
                   total_cost_usd, gate_pass, summary, raw_payload
            FROM run_logs
            WHERE demo IN ({placeholders})
            ORDER BY id DESC
            LIMIT ?
            """,
            (*demos, limit),
        ).fetchall()
    out: list[dict[str, Any]] = []
    for row in rows:
        item = dict(row)
        try:
            item["payload"] = json.loads(item.pop("raw_payload") or "{}")
        except json.JSONDecodeError:
            item["payload"] = {}
        out.append(item)
    return list(reversed(out))


def get_run_by_id(run_id: int, db_path: Path = DB_PATH) -> dict[str, Any] | None:
    init_db(db_path)
    with sqlite3.connect(db_path) as conn:
        conn.row_factory = sqlite3.Row
        row = conn.execute("SELECT * FROM run_logs WHERE id = ?", (run_id,)).fetchone()
        if not row:
            return None
        item = dict(row)
        try:
            item["payload"] = json.loads(item.pop("raw_payload") or "{}")
        except json.JSONDecodeError:
            item["payload"] = {}
        return item
